export {default as Home} from "./Home"
export {default as Login} from "./Login"
export {default as Register} from "./Register"
export {default as DriverLogin} from "./driverLogin"
export {default as DriverRegister} from "./driverRegister"